### ISSUE TITLE
Button for creating a shareable link

### ISSUE THREAD

**Issue by evannorton** [retro-mmo-com/vod-player#11]
This should include both an option for linking at the current timestamp, and an option for linking from the beginning fo the VOD.

**Comment by ERmilburn02** [comment]
Do we want 2 separate buttons, or a popup, or a checkbox next to the button?

**Comment by TheGetitGuy** [comment]
It's a shame we couldn't add it to the controls already on the video.

**Comment by ERmilburn02** [comment]
> It's a shame we couldn't add it to the controls already on the video. 

The controls on the video are currently the browser default, we would have to make completely custom controls.

**Comment by TheGetitGuy** [comment]
> > It's a shame we couldn't add it to the controls already on the video.
> 
> The controls on the video are currently the browser default, we would have to make completely custom controls.

https://codepen.io/thegetitguy/pen/NWYyRmQ    
Something like this. Its probably out of scope for this project? maybe the share button could be put under or on top of the chat?

**Comment by ERmilburn02** [comment]
> maybe the share button could be put under or on top of the chat?
I looked a little into this, it could work.
